version: '3.8'
services:
  backend:
    volumes:
      - ./backend/sosdata.db:/app/sosdata.db
      - ./backend:/app
    build: ./backend
    ports:
      - "3000:5000"
    environment:
      - NODE_ENV=production

  frontend:
    build: ./frontend
    ports:
      - "8080:80"
